(define (default-eval exp env)
  (cond ((or (number? exp) (boolean? exp) (string? exp)) exp)
        ((symbol? exp) (cdr (assoc exp (apply append env))))
        ((list? exp)
         (case (car exp)
           ((quote) (cadr exp))
	   ((cons) (cons (default-eval (cadr exp) env)
			 (default-eval (caddr exp) env)))
	   ((car) (car (default-eval (cadr exp) env)))
	   ((cdr) (cdr (default-eval (cadr exp) env)))
	   ((if) (if (default-eval (cadr exp) env)
		     (default-eval (caddr exp) env)
		     (default-eval (cadddr exp) env)))
	   ((atom?) (not (pair? (default-eval (cadr exp) env))))
	   ((eq?) (eq? (default-eval (cadr exp) env)
		       (default-eval (caddr exp) env)))
	   ((lambda) `((env . ,env)
		       (params . ,(cadr exp))
		       (body . ,(cddr exp))))
	   ((define) (set-car! env (acons (cadr exp)
					  (default-eval (caddr exp) env)
					  (car env))))
	   (else (default-apply (default-eval (car exp) env)
		   (map (lambda (exp) (default-eval exp env))
			(cdr exp))))))
	(else (error (format #f "I dont know how to handle ~a" exp)))))

(define (default-apply proc args)
  (let ((new-env (cons (map cons (cdr (assoc 'params proc)) args)
		       (cdr (assoc 'env proc)))))
    (car (reverse (map (lambda (statement) (default-eval statement new-env))
		       (cdr (assoc 'body proc)))))))
