(define (nth n seq)
  (if (zero? n)
      (car seq)
      (nth (1- n) (cdr seq))))

;;; reflective eval implements a reflective tower.  The way this works
;;; is that a call from reflect causes a 1-directional jump out of the
;;; current level into the meta level.  The expression passed to
;;; reflect is evaluated in the meta level, and is typically of the
;;; form (lambda (env k) ...)
;;;
;;; To access variables from the object level below, the procedure
;;; should find them in the env, which represents the environment of
;;; the object code.
;;;
;;; Eval is also extended to take 3 arguments: an environment to
;;; evaluate code under, an expression to evaluate, and a continuation
;;; representing the rest of the computation.
;;;
;;; Reflective-eval represents the continuation as a stack, which
;;; provides for easier inspection in the meta-level.
;;;
;;; after work has been done at the meta-level, the typical approach
;;; is to re-enter the object level by calling eval with the
;;; environment and continuation passed up to the meta level and the
;;; result of any work done in the meta level.
;;;
;;; This approach allows the implementation of call/cc, define for
;;; hyper-static environments, and set! without requiring any of these
;;; as primitive functions in the interpreter, allowing it to stay
;;; purely functional.
(define (reflective-eval exp env stack-model)
  ;; these represent dynamic exit points when reflect is called.  the
  ;; stack unwinds to the nearest eval or all the way up to here,
  ;; which meant that no current meta-level exists. If that occurs,
  ;; this top level block will generate a new meta level by recurring
  ;; and then continue execution.
  (with-exception-handler
      ;; build meta environment on demand if requested
      (lambda (exn)
        (if (and (list? exn)
		 (eq? (car exn) 'reflect))
	    (reflective-eval (cadr exn) (list (list)) '())
	    (raise-exception exn)))
    (lambda ()
      (default-eval exp env stack-model))
    #:unwind? #t))

;; this is the bulk of the interpreter, which runs in the forward
;; direction. The continuation is generated by having stack-model
;; shadow the state of this interpreter, which means no explicit
;; continuation has to be constructed or followed, dramatically
;; simplifying the implmentation and improving performance, since
;; computation can proceed on a stack machine model.
(define (default-eval exp env stack-model)
  (cond ((or (number? exp) (boolean? exp) (string? exp))
	 exp)
	((symbol? exp) (let ((it (assoc exp (apply append env))))
			 (if it
			     (cdr it)
			     (raise-exception (format #f "failed to locate ~a" exp)))))
	((list? exp)
	 (case (car exp)
	   ;; quote is tail recursive so no stack frame is generated
	   ((quote) (cadr exp))
	   ((cons) (let* ((a1 (default-eval (cadr exp) env (cons `(,exp 1) stack-model)))
			  (a2 (default-eval (caddr exp) env (cons `((cons ,a1 ,(caddr exp)) 2)
								  stack-model))))
		     (cons a1 a2)))
	   ((car) (car (default-eval (cadr exp) env (cons `(,exp 1) stack-model))))
	   ((cdr) (cdr (default-eval (cadr exp) env (cons `(,exp 1) stack-model))))
	   ;; if is tail recurisve so the stack frame doesn't persist after a1
	   ((if) (let ((a1 (default-eval (cadr exp) env (cons `(,exp 1) stack-model))))
		   (if a1
		       (default-eval (caddr exp) env stack-model)
		       (default-eval (cadddr exp) env stack-model))))
	   ((atom?) (not (pair? (default-eval (cadr exp) env (cons `(,exp 1) stack-model)))))
	   ((eq?) (let* ((a1 (default-eval (cadr exp) env (cons `(,exp 1) stack-model)))
			 (a2 (default-eval (caddr exp) env (cons `((eq? ,a1 ,(caddr exp)) 2) stack-model))))
		    (eq? a1 a2)))
	   ;; generating a lambda can be done without a stack
	   ((lambda) `((env . ,env)
		       (params . ,(cadr exp))
		       (body . (begin ,@(cddr exp)))))
	   ((begin) (do ((statements (cdr exp) (cdr statements))
			 (i 1 (1+ i)))
			((null? (cdr statements)) (default-eval (car statements)
						    env
						    `((,exp ,i) ,@stack-model)))
			(default-eval (car statements) env `((,exp ,i) ,@stack-model))))
	   ((reflect) 		; reflection reifies the
					; execution state and env, and passes them explicitly to
					; the arg which executes in the immediate
					; meta-level.
	    ;;
	    ;; this is done by unwinding the stack dynamically to
	    ;; either the innermost eval point or all the way up and
	    ;; generating a new meta-level.
            (let ((a1 (default-eval (cadr exp)
			env (cons `((reflect ,(cadr exp)) 1) stack-model))))
	      (raise-exception `(reflect (,(cadr exp) ',env ',stack-model)))))
	   ((eval)  
	    (let* ((a1 (default-eval (cadr exp) env (cons `(,exp 1) stack-model)))
		   (a2 (default-eval (caddr exp) env (cons `((eval ,a1 ,(caddr exp)) 2)
							   stack-model)))
		   (a3 (default-eval (cadddr exp)
			 env
			 (cons `((eval ,a1 ,a2 ,(cadddr exp)) 3)
			       stack-model))))
	      ;; create a new point for reflect to jump to. We're at
	      ;; the object level right now, and will be evaling code
	      ;; in the sub-object level.
	      ;;
	      ;; If that code calls reflect, we'll catch it here and
	      ;; run that code at the object level.
              (with-exception-handler
		  (lambda (exn)
                    (if (and (list? exn)
			     (eq? (car exn) 'reflect))
			(default-eval (cadr exn) env '())
			(raise-exception exn)))
		(lambda ()
		  (finish-computation a1 a2 (default-eval a3 a2 '())))
		#:unwind? #t)))
	   ;; else its function application
	   (else (let* ((proc (default-eval (car exp) env (cons `(,exp 0) stack-model)))
			(args (do ((evaluated '() (cons (default-eval (car args)
							  env (cons `((,proc ,@(reverse evaluated) ,@args) i)
								    stack-model) )
							evaluated))
				   (args (cdr exp) (cdr args))
				   (i 1 (1+ i)))
				  ((null? args) (reverse evaluated)))))
                   (default-apply proc args stack-model)))))
	(else (error (format #f "I dont know how to handle ~a" exp)))))

;; just a standard apply function
(define (default-apply proc args stack-model)
  (let ((new-env (cons (map cons (cdr (assoc 'params proc)) args)
		       (cdr (assoc 'env proc)))))
    (default-eval (cdr (assoc 'body proc)) new-env stack-model)))

(define (substitute list n v)
  (do ((list list (cdr list))
       (result '() (cons (if (= i n) v (car list)) result))
       (i 0 (1+ i)))
      ((null? list) (reverse result))))

;; this is a special routine used to follow the continuation. It
;; reduces the stack until its empty and returns the final result.
;; each unevaluated sub-expression is followed forward using default-eval and
;; the stack is reduced frame by frame until exhausted.
;;
;; this mechanism is what allows eval to follow a continuation passed into it.
(define (finish-computation env stack-model result)
  (let compute ((stack-model stack-model)
		(result result))
    (if (null? stack-model)
	result
	(let* ((top-frame (car stack-model))
	       (expr (car top-frame))
	       (i (cadr top-frame))
	       (next-expr (if (>= (1+ i) (length expr)) #f (nth (1+ i) expr)))
	       (continue (lambda ()
                           (let* ((next-stack `((,(substitute expr i result) ,(1+ i)) ,@(cdr stack-model)))
				  (next-val (if (> (length expr) (1+ i))
						(default-eval (nth (1+ i) expr) env next-stack)
						(compute next-stack '()))))
                             (compute next-stack next-val)))))
          (case (car expr)
	    ((car) (if (< i 2) (continue)
		       (compute (cdr stack-model)
				(car (cadr expr)))))
	    ((cdr) (if (< i 2) (continue)
		       (compute (cdr stack-model)
				(cdr (cadr expr)))))
	    ((cons) (if (< i 3) (continue)
			(compute ( cdr stack-model)
				 (cons (cadr expr)
				       (caddr expr)))))
	    ((if) (if (< i 2) (continue)
		      (compute (cdr stack-model)
			       (if (cadr expr)
				   (if (= 2 i)
				       result
				       (default-eval (caddr expr) env (cdr stack-model)))
				   (if (= 3 i)
				       result
				       (default-eval (cadddr expr) env (cdr stack-model)))))))
	    ((atom?) (if (< i 2) (continue)
			 (compute (cdr stack-model)
				  (not (pair? (cadr expr))))))
	    ((eq?) (if (< i 3) (continue)
		       (compute (cdr stack-model)
				(eq? (cadr expr)
				     (caddr expr)))))
	    ((reflect) 
	     (if (< i 2) (continue)
			   (raise-exception `(reflect (',(cadr exp) ',env ',stack-model)) )))
	    ((begin)
	     (if (< i (1- (length expr))) (continue)
		 (compute (cdr stack-model)
			  result)))
	    (else (if (= i (length expr))
		      (default-apply (car expr) (cdr expr)
			(cdr stack-model)))))))))



