(define (reflective-eval exp env stack-model)
  (with-exception-handler
      ;; build meta environment on demand if requested
      (lambda (exn)
        (if (and (list? exn)
		 (eq? (car exn) 'reflect))
	    (reflective-eval (cadr exn) (list (list)) '())
	    (raise-exception exn)))
    (lambda ()
      (default-eval exp env stack-model))
    #:unwind? #t))

(define (default-eval exp env stack-model)
  (cond ((or (number? exp) (boolean? exp) (string? exp))
	 exp)
	((symbol? exp)  (cdr (assoc exp (apply append env))))
	((list? exp)
	 (case (car exp)
	   ;; quote is tail recursive so no stack frame is generated
	   ((quote) (cadr exp))
	   ((cons) (let* ((a1 (default-eval (cadr exp) env (cons `(,exp 1) stack-model)))
			  (a2 (default-eval (caddr exp) env (cons `((cons ,a1 ,(caddr exp)) 2)
								  stack-model))))
		     (cons a1 a2)))
	   ((car) (car (default-eval (cadr exp) env (cons `(,exp 1) stack-model))))
	   ((cdr) (cdr (default-eval (cadr exp) env (cons `(,exp 1) stack-model))))
	   ;; if is tail recurisve so the stack frame doesn't persist after a1
	   ((if) (let ((a1 (default-eval (cadr exp) env (cons `(,exp 1) stack-model))))
		   (if a1
		       (default-eval (caddr exp) env stack-model)
		       (default-eval (cadddr exp) env stack-model))))
	   ((atom?) (not (pair? (default-eval (cadr exp) env (cons `(,exp 1) stack-model)))))
	   ((eq?) (let* ((a1 (default-eval (cadr exp) env (cons `(,exp 1) stack-model)))
			 (a2 (default-eval (caddr exp) env (cons `((eq? ,a1 ,(caddr exp)) 2) stack-model))))
		    (eq? a1 a2)))
	   ;; generating a lambda can be done without a stack
	   ((lambda) `((env . ,env)
		       (params . ,(cadr exp))
		       (body . ,(cddr exp))))
	   ((define) (let ((a1 (default-eval (caddr exp) env (cons `((define ,(cadr exp) ,(caddr exp)) 2) stack-model))))
		       (set-car! env (acons (cadr exp) a1 (car env)))))
	   ((reflect) 		; reflection reifies the
					; execution state and env, and passes them explicitly to
					; the arg which executes in the immediate
					; meta-level. I.e., if this code is running inside an
					; eval block, it no longer will be.
	    (let ((a1 (default-eval (cadr exp)
			 env (cons `((reflect ,(cadr exp)) 1) stack-model))))
	      (raise-exception `(reflect (,(cadr exp) ',env ',stack-model)))))
	   ((eval)  
	    (let* ((a1 (default-eval (cadr exp) env (cons `(,exp 1) stack-model)))
		   (a2 (default-eval (caddr exp) env (cons `((eval ,a1 ,(caddr exp)) 2)
							   stack-model)))
		   (a3 (default-eval (cadddr exp)
			 env
			 (cons `((eval ,a1 ,a2 ,(cadddr exp)) 3)
			       stack-model))))
              (with-exception-handler
		  ;; support returning to object level from
		  ;; the sub-object level while retaining
		  ;; context
		  (lambda (exn)
                    (if (and (list? exn)
			     (eq? (car exn) 'reflect))
			(default-eval (cadr exn) env '())
			(raise-exception exn)))
		(lambda ()
		  (finish-computation a1 a2 (default-eval a3 a2 '())))
		#:unwind? #t)))
	   (else (let* ((proc (default-eval (car exp) env (cons `(,exp 0) stack-model)))
			(args (do ((evaluated '() (cons (default-eval (car args)
							  env (cons `((,proc ,@(reverse evaluated) ,@args) i)
								    stack-model) )
							evaluated))
				   (args (cdr exp) (cdr args))
				   (i 1 (1+ i)))
				  ((null? args) (reverse evaluated)))))
                   (default-apply proc args stack-model)))))
	(else (error (format #f "I dont know how to handle ~a" exp)))))

(define (default-apply proc args stack-model)
  (let ((new-env (cons (map cons (cdr (assoc 'params proc)) args)
		       (cdr (assoc 'env proc)))))
    (car (reverse (map (lambda (statement)
                         (default-eval statement new-env stack-model))
		       (cdr (assoc 'body proc)))))))

(define (substitute list n v)
  (do ((list list (cdr list))
       (result '() (cons (if (= i n) v (car list)) result))
       (i 0 (1+ i)))
      ((null? list) (reverse result))))

(define (finish-computation env stack-model result)
  (let compute ((stack-model stack-model)
		(result result))
    (if (null? stack-model)
	result
	(let* ((top-frame (car stack-model))
	       (expr (car top-frame))
	       (i (cadr top-frame))
	       (next-expr (if (>= (1+ i) (length expr)) #f (nth (1+ i) expr)))
	       (continue (lambda ()
                           (let* ((next-stack `((,(substitute expr i result) ,(1+ i)) ,@(cdr stack-model)))
				  (next-val (if (>= (length expr) (1+ i))
						(compute next-stack '())
						(default-eval (nth (1+ i) expr) env next-stack))))
			     (compute next-stack next-val)))))
          (case (car expr)
	    ((car) (if (< i 2) (continue)
		       (compute (cdr stack-model)
				(car (cadr expr)))))
	    ((cdr) (if (< i 2) (continue)
		       (compute (cdr stack-model)
				(cdr (cadr expr)))))
	    ((cons) (if (< i 3) (continue)
			(compute ( cdr stack-model)
				 (cons (cadr expr)
				       (caddr expr)))))
	    ((if) (if (< i 2) (continue)
		      (compute (cdr stack-model)
			       (if (cadr expr)
				   (if (= 2 i)
				       result
				       (default-eval (caddr expr) env (cdr stack-model)))
				   (if (= 3 i)
				       result
				       (default-eval (cadddr expr) env (cdr stack-model)))))))
	    ((atom?) (if (< i 2) (continue)
			 (compute (cdr stack-model)
				  (not (pair? (cadr expr))))))
	    ((eq?) (if (< i 3) (continue)
		       (compute (cdr stack-model)
				(eq? (cadr expr)
				     (caddr expr)))))
	    ((define) (compute (cdr stack-model)
			       (set-car! env (acons (cadr exp)
						    (if (< i 2)
							(default-eval (caddr expr) env (cdr stack-model))
							(caddr expr))
						    (car env)))))
	    ((reflect) (if (< i 2) (continue)
			   (raise-exception `(reflect (',(cadr exp) ',env ',stack-model)) )))
	    (else
	     (if (= i (length expr))
		 (default-apply (car expr) (cdr expr)
		   (cdr stack-model))
		 (continue))))))))
